const bookList=document.querySelector('#book-list'),addBookForm=document.querySelector('#add-book-form'),coverInput=document.querySelector('[name="cover"]'),coverStatus=document.querySelector('#new-cover-status'),bookFormStatus=document.querySelector('#book-form-status'),submitButton=document.querySelector('#book-submit'),cancelEdit=document.querySelector('#cancel-edit'),formKicker=document.querySelector('#form-kicker');let editingId=null;let featuredBookId=null;let rotationTimer=null;const seedBooks=[{id:'seed-1',title:'The Remains of the Day',author:'Kazuo Ishiguro',thought:'A restrained and quietly devastating book about duty, memory, and the cost of leaving things unsaid.',cover:''},{id:'seed-2',title:'Kitchen',author:'Banana Yoshimoto',thought:'A small, gentle refuge of a book — full of grief, warmth, and ordinary rooms that hold people together.',cover:''},{id:'seed-3',title:'Pachinko',author:'Min Jin Lee',thought:'A sweeping family story that makes history feel intimate, fragile, and deeply personal.',cover:''}];let books=JSON.parse(localStorage.getItem('nomelon-all-books')||'null')||seedBooks;if(!localStorage.getItem('nomelon-all-books')) books.unshift({id:'original-feature',title:'Norwegian Wood',author:'Haruki Murakami',year:'1987',publisher:'VINTAGE',thought:'If you only read the books that everyone else is reading, you can only think what everyone else is thinking.',cover:'',starred:true});const saveBooks=()=>localStorage.setItem('nomelon-all-books',JSON.stringify(books));
const setFeature=book=>{featuredBookId=book.id;const cover=document.querySelector('#featured-cover');if(!cover)return;document.querySelector('#featured-label').textContent='Selected from my bookshelf';document.querySelector('#featured-title').textContent=book.title;document.querySelector('#featured-meta').textContent=[book.author,book.year].filter(Boolean).join(' · ');document.querySelector('#featured-thought').textContent=`“${book.thought}”`;document.querySelector('#featured-author').textContent=book.author.toUpperCase();document.querySelector('#featured-title-cover').textContent=book.title;document.querySelector('#featured-cover small').textContent=book.publisher||'';cover.classList.add('active-cover');if(book.cover){cover.classList.add('has-image');cover.style.backgroundImage=`url('${book.cover}')`}else{cover.classList.remove('has-image');cover.style.backgroundImage=''}};const startEdit=book=>{clearInterval(rotationTimer);editingId=book.id;coverInput.value='';addBookForm.elements.year.value=book.year||'';addBookForm.elements.publisher.value=book.publisher||'';addBookForm.elements.title.value=book.title;addBookForm.elements.author.value=book.author;addBookForm.elements.thought.value=book.thought;coverStatus.textContent=book.cover?'Current cover will be kept unless you choose a new one.':'No cover selected — a typographic cover will be created.';submitButton.innerHTML='Save changes <span>↑</span>';formKicker.textContent='Edit this book';cancelEdit.hidden=false;addBookForm.scrollIntoView({behavior:'smooth',block:'center'})};
const renderBooks=()=>{if(!bookList)return;bookList.innerHTML='';books.forEach((book,index)=>{const entry=document.createElement('article');entry.className=`book-entry ${book.cover?'custom':''}`;const coverMarkup=book.cover?`<span class="mini-cover" style="background-image:url('${book.cover}')"></span>`:'';entry.innerHTML=`<button class="star-book" type="button" aria-pressed="${!!book.starred}">${book.starred?'★':'☆'}</button><button class="book-toggle" type="button" aria-expanded="false"><span>${String(index+1).padStart(2,'0')}</span>${coverMarkup}<strong></strong><small></small><i>+</i></button><div class="book-thought"><p></p></div><div class="book-actions"><button type="button" class="edit-book">Edit</button><button type="button" class="delete-book">Delete</button></div>`;const star=entry.querySelector('.star-book');star.setAttribute('aria-label',`${book.starred?'Unstar':'Star'} ${book.title} for the featured shelf`);star.onclick=()=>{book.starred=!book.starred;saveBooks();renderBooks();restartRotation()};entry.querySelector('strong').textContent=book.title;entry.querySelector('small').textContent=book.author;entry.querySelector('.book-thought p').textContent=`“${book.thought}”`;entry.querySelector('.book-toggle').onclick=()=>{const open=entry.classList.toggle('open');entry.querySelector('.book-toggle').setAttribute('aria-expanded',open);};entry.querySelector('.edit-book').onclick=()=>startEdit(book);entry.querySelector('.delete-book').onclick=()=>{books=books.filter(item=>item.id!==book.id);saveBooks();renderBooks();restartRotation();bookFormStatus.textContent=`${book.title} has been removed from your private bookshelf.`};bookList.append(entry)})};
const resetBookForm=()=>{editingId=null;addBookForm?.reset();coverStatus.textContent='No cover selected — a typographic cover will be created.';submitButton.innerHTML='Add to my bookshelf <span>↑</span>';formKicker.textContent='Add to the shelf';cancelEdit.hidden=true};cancelEdit?.addEventListener('click',()=>{resetBookForm();restartRotation()});coverInput?.addEventListener('change',()=>coverStatus.textContent=coverInput.files[0]?`Cover selected: ${coverInput.files[0].name}`:'No cover selected — a typographic cover will be created.');addBookForm?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(addBookForm),existing=books.find(book=>book.id===editingId),book={...existing,year:data.get('year').trim(),publisher:data.get('publisher').trim(),id:editingId||crypto.randomUUID(),title:data.get('title').trim(),author:data.get('author').trim(),thought:data.get('thought').trim(),cover:existing?.cover||''},file=coverInput.files[0];const finish=()=>{if(editingId){books=books.map(item=>item.id===editingId?book:item);bookFormStatus.textContent=`${book.title} has been updated.`}else{books.push(book);bookFormStatus.textContent=`${book.title} has been added to your private bookshelf.`}saveBooks();renderBooks();resetBookForm();restartRotation()};if(file){if(file.size>900000){bookFormStatus.textContent='Please choose an image smaller than 900 KB so it can be saved privately in this browser.';return}const reader=new FileReader();reader.onload=()=>{book.cover=reader.result;finish()};reader.readAsDataURL(file)}else finish()});

function restartRotation() {
  clearInterval(rotationTimer);
  const selected=books.filter(book=>book.starred);
  const featured=selected.length?selected:books.slice(0,1);
  if (!featured.length) {
    featuredBookId=null;
    document.querySelector('#featured-title').textContent='Your shelf starts here';
    document.querySelector('#featured-meta').textContent='Add a book below to get started.';
    document.querySelector('#featured-thought').textContent='';
    document.querySelector('#featured-label').textContent='My bookshelf';
    const cover=document.querySelector('#featured-cover');
    cover.style.backgroundImage='';cover.classList.remove('has-image');
    cover.querySelectorAll('span,b,small').forEach(node=>node.textContent='');
  } else {
    let index=0;setFeature(featured[index]);
    if(featured.length>1) rotationTimer=setInterval(()=>{index=(index+1)%featured.length;setFeature(featured[index])},5000);
  }
  document.querySelector('#edit-featured-book').disabled=!featuredBookId;
  document.querySelector('#featured-cover-input').disabled=!featuredBookId;
}
document.querySelector('#edit-featured-book').onclick=()=>{
  const book=books.find(book=>book.id===featuredBookId);if(book)startEdit(book);
};
const featuredInput=document.querySelector('#featured-cover-input');
featuredInput.addEventListener('change',()=>{
  const file=featuredInput.files[0],book=books.find(book=>book.id===featuredBookId);
  if(!file||!book)return;
  if(file.size>900000){bookFormStatus.textContent='Please choose an image smaller than 900 KB.';featuredInput.value='';return;}
  clearInterval(rotationTimer);
  const reader=new FileReader();
  reader.onload=()=>{book.cover=reader.result;saveBooks();renderBooks();restartRotation();featuredInput.value=''};
  reader.onerror=()=>{bookFormStatus.textContent='Unable to read this image. Please try again.';restartRotation()};
  reader.readAsDataURL(file);
});
renderBooks();restartRotation();
