// Use the visitor's device clock and timezone; refresh across midnight and resume.
const localDateLabel = document.querySelector('.hero .date');
if (localDateLabel) {
  const updateLocalDate = () => {
    localDateLabel.textContent = new Intl.DateTimeFormat('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
    }).format(new Date());
  };
  updateLocalDate();
  setInterval(updateLocalDate, 1000);
  document.addEventListener('visibilitychange', updateLocalDate);
  window.addEventListener('pageshow', updateLocalDate);
}
const nav=document.querySelector('.nav');addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>30),{passive:true});const themeButton=document.querySelector('.theme-toggle');themeButton?.addEventListener('click',()=>{document.body.classList.toggle('night');themeButton.textContent=document.body.classList.contains('night')?'◐':'☼'});
const places={Japan:'Books, films and little details I want to bring home from here.',Italy:'A long table, an old cinema, and a language made for lingering.',France:'New Wave frames, quiet cafés, and the art of looking carefully.',Iceland:'Wind, midnight light, and music that feels like a landscape.'};document.querySelectorAll('.pin').forEach(pin=>pin.addEventListener('click',()=>{document.querySelector('#place-name').textContent=pin.dataset.place;document.querySelector('#place-copy').textContent=places[pin.dataset.place]}));
const form=document.querySelector('#message-form'),imageInput=document.querySelector('#image-upload'),fileStatus=document.querySelector('#file-status'),recordButton=document.querySelector('#record-button'),sendStatus=document.querySelector('#send-status');let recorder,voiceBlob;imageInput?.addEventListener('change',()=>{fileStatus.textContent=imageInput.files[0]?`Image ready: ${imageInput.files[0].name}`:''});recordButton?.addEventListener('click',async()=>{if(recorder?.state==='recording'){recorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{voiceBlob=new Blob(chunks,{type:'audio/webm'});fileStatus.textContent='Voice note ready';recordButton.textContent='Record a new voice note';stream.getTracks().forEach(track=>track.stop())};recorder.start();recordButton.textContent='Stop recording';fileStatus.textContent='Recording…'}catch{fileStatus.textContent='Microphone access was not available.'}});form?.addEventListener('submit',e=>{e.preventDefault();sendStatus.textContent='Your private note has been sent in demo mode. Email delivery is not connected yet.';form.reset();voiceBlob=null;fileStatus.textContent='';recordButton.textContent='Record a voice note'});
const trackList=document.querySelector('#track-list'),addTrackForm=document.querySelector('#add-track-form'),trackCoverInput=document.querySelector('#add-track-form [name="cover"]'),trackAudioInput=document.querySelector('#add-track-form [name="audio"]'),trackCoverStatus=document.querySelector('#music-cover-status'),trackAudioStatus=document.querySelector('#music-audio-status'),trackFormStatus=document.querySelector('#track-form-status'),trackSubmit=document.querySelector('#track-submit'),cancelTrackEdit=document.querySelector('#cancel-track-edit'),musicKicker=document.querySelector('#music-form-kicker');let editingTrack=null;const seedTracks=[{id:'track-1',title:'Weird Fishes / Arpeggi',artist:'Radiohead',album:'In Rainbows',thought:'A record for when the world feels slightly unreal.',cover:''},{id:'track-2',title:'First Love',artist:'Utada Hikaru',album:'First Love',thought:'A song that holds sadness and softness in the same breath.',cover:''},{id:'track-3',title:'Pink + White',artist:'Frank Ocean',album:'Blonde',thought:'Sunlight, memory, and the feeling of a summer that is already gone.',cover:''}];let tracks=JSON.parse(localStorage.getItem('nomelon-tracks')||'null')||seedTracks;const saveTracks=()=>localStorage.setItem('nomelon-tracks',JSON.stringify(tracks));
const setTrackFeature=track=>{if(!document.querySelector('#track-title'))return;document.querySelector('#track-label').textContent='Selected from my playlist';document.querySelector('#track-title').textContent=track.title;document.querySelector('#track-meta').textContent=[track.artist,track.album].filter(Boolean).join(' · ');document.querySelector('#track-thought').textContent=`“${track.thought}”`;document.querySelector('#featured-album-name').innerHTML=(track.album||track.title).toUpperCase().replace(' ','<br/>');const album=document.querySelector('#featured-album');if(track.cover){album.style.backgroundImage=`url('${track.cover}')`;album.style.backgroundSize='cover';album.querySelector('span').style.visibility='hidden'}else{album.style.backgroundImage='';album.querySelector('span').style.visibility='visible'}};
const startTrackEdit=track=>{editingTrack=track.id;addTrackForm.elements.title.value=track.title;addTrackForm.elements.artist.value=track.artist;addTrackForm.elements.album.value=track.album||'';addTrackForm.elements.thought.value=track.thought;trackCoverStatus.textContent=track.cover?'Current cover will be kept unless you choose a new one.':'No cover selected — a typographic cover will be created.';trackSubmit.innerHTML='Save changes <span>↑</span>';musicKicker.textContent='Edit this track';cancelTrackEdit.hidden=false;addTrackForm.scrollIntoView({behavior:'smooth',block:'center'})};
const renderTracks=()=>{if(!trackList)return;trackList.innerHTML='';tracks.forEach((track,index)=>{const entry=document.createElement('article');entry.className='track-entry';entry.innerHTML=`<button class="track-toggle" type="button" aria-expanded="false"><span>${String(index+1).padStart(2,'0')}</span><strong></strong><small></small><i>+</i></button><div class="track-thought"><p></p></div><div class="track-actions"><button type="button" class="edit-track">Edit</button><button type="button" class="delete-track">Delete</button></div>`;entry.querySelector('strong').textContent=track.title;entry.querySelector('small').textContent=track.artist;entry.querySelector('.track-thought p').textContent=`“${track.thought}”`;entry.querySelector('.track-toggle').onclick=()=>{const open=entry.classList.toggle('open');entry.querySelector('.track-toggle').setAttribute('aria-expanded',open);setTrackFeature(track)};entry.querySelector('.edit-track').onclick=()=>startTrackEdit(track);entry.querySelector('.delete-track').onclick=()=>{tracks=tracks.filter(item=>item.id!==track.id);saveTracks();renderTracks();trackFormStatus.textContent=`${track.title} has been removed from your private playlist.`};trackList.append(entry)})};renderTracks();
const resetTrackForm=()=>{editingTrack=null;addTrackForm?.reset();trackCoverStatus.textContent='No cover selected — a typographic cover will be created.';trackAudioStatus.textContent='No audio selected — this entry will remain informational.';trackSubmit.innerHTML='Add to my playlist <span>↑</span>';musicKicker.textContent='Add to the playlist';cancelTrackEdit.hidden=true};cancelTrackEdit?.addEventListener('click',resetTrackForm);trackCoverInput?.addEventListener('change',()=>trackCoverStatus.textContent=trackCoverInput.files[0]?`Cover selected: ${trackCoverInput.files[0].name}`:'No cover selected — a typographic cover will be created.');trackAudioInput?.addEventListener('change',()=>trackAudioStatus.textContent=trackAudioInput.files[0]?`Audio selected: ${trackAudioInput.files[0].name} (information only in this demo)`: 'No audio selected — this entry will remain informational.');addTrackForm?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(addTrackForm),existing=tracks.find(track=>track.id===editingTrack),track={id:editingTrack||crypto.randomUUID(),title:data.get('title').trim(),artist:data.get('artist').trim(),album:data.get('album').trim(),thought:data.get('thought').trim(),cover:existing?.cover||''},file=trackCoverInput.files[0];const finish=()=>{if(editingTrack){tracks=tracks.map(item=>item.id===editingTrack?track:item);trackFormStatus.textContent=`${track.title} has been updated.`}else{tracks.push(track);trackFormStatus.textContent=`${track.title} has been added to your private playlist.`}saveTracks();renderTracks();setTrackFeature(track);resetTrackForm()};if(file){if(file.size>900000){trackFormStatus.textContent='Please choose a cover image smaller than 900 KB for this browser-only library.';return}const reader=new FileReader();reader.onload=()=>{track.cover=reader.result;finish()};reader.readAsDataURL(file)}else finish()});
const footer=document.querySelector('footer');if(footer){const oldCopy=footer.querySelector('p'),oldLinks=footer.querySelector('div:not(.footer-monogram)'),reflection=document.createElement('blockquote');reflection.className='footer-reflection';reflection.innerHTML='<span class="footer-question">Have we ever met before?</span><span class="footer-answer">Well, you say we have not—but perhaps that is only because we have forgotten, or never noticed. And what is forgotten or unnoticed is much the same as never having happened.</span>';oldCopy?.replaceWith(reflection);oldLinks?.remove()}
